@extends('email.email-layout')

@section('title', $title)

@section("content")
<!--[if (mso)|(IE)]><td align="center" width="600" style="width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
<div
    class='u-col u-col-100'
    style='max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;'>
    <div style='height: 100%;width: 100% !important;'>
        <!--[if (!mso)&(!IE)]><!-->
        <div
            style='box-sizing: border-box; height: 100%; padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;'><!--<![endif]-->

            <table
                style="font-family:'Lato',sans-serif;"
                role='presentation'
                cellpadding='0'
                cellspacing='0'
                width='100%'
                border='0'>
                <tbody>
                    <tr>
                        <td
                            style="overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;"
                            align='left'>

                            <div style='line-height: 140%; text-align: left; word-wrap: break-word;'>
                                <p style='font-size: 14px; line-height: 140%;'>
                                    <span style='font-size: 18px; line-height: 25.2px; color: #666666;'>
                                        Please DO NOT REPLY as this is an autogenerated message.
                                    </span>
                                </p>

                                <p style='font-size: 14px; line-height: 140%;'> </p>

                                <p style='font-size: 14px; line-height: 140%;'>
                                    <span style='font-size: 18px; line-height: 25.2px; color: #666666;'>
                                        Dear {{ $name }},
                                    </span>
                                </p>


                                <p style='font-size: 14px; line-height: 140%;'> </p>

                                <p
                                    style='font-size: 14px; line-height: 140%;'>
                                    <span
                                        style='font-size: 18px; line-height: 25.2px; color: #666666;'>
                                        Your One-Time Password (OTP) is:
                                    </span>
                                </p>

                                <p style='font-size: 14px; line-height: 140%;'> </p>

                                <p
                                    style='font-size: 14px; line-height: 140%; text-align:center'>
                                    <span
                                        style='font-size: 45px; line-height: 25.2px; color: #333;'>
                                        {{ $otp }}
                                    </span>
                                </p>

                                <p style='font-size: 14px; line-height: 140%;'> </p>

                                <p style='font-size: 14px; line-height: 140%;'>
                                    <span
                                        style='font-size: 18px; line-height: 25.2px; color: #666666;'>
                                        Please use your OTP to complete your login. Do not share this code with anyone.
                                    </span>
                                </p>

                                <p style='font-size: 14px; line-height: 140%;'> </p>

                                <p
                                    style='font-size: 14px; line-height: 140%;'>
                                    <span
                                        style='font-size: 18px; line-height: 25.2px; color: #666666;'>
                                        Regards,<br />
                                        Semporna Jetty
                                    </span>
                                </p>


                            </div>

                        </td>
                    </tr>
                </tbody>
            </table>



            <!--[if (!mso)&(!IE)]><!-->
        </div><!--<![endif]-->
    </div>
</div>
@endsection
